# TCL File Generated by Component Editor 18.1
# Sat Nov 17 19:50:20 CET 2018
# DO NOT MODIFY


# 
# hdc1000 "hdc1000" v1.0
# SSL-HW-Group 2018.11.17.19:50:20
# Temperature/Humidity Sensor
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hdc1000
# 
set_module_property DESCRIPTION "Temperature/Humidity Sensor"
set_module_property NAME hdc1000
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SSL
set_module_property AUTHOR SSL-HW-Group
set_module_property DISPLAY_NAME hdc1000
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hdc1000AvalonInterface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdc1000AvalonInterface.vhd VHDL PATH components/hdc1000/hdc1000AvalonInterface.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL hdc1000AvalonInterface
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hdc1000AvalonInterface.vhd VHDL PATH components/hdc1000/hdc1000AvalonInterface.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point hdc1000_s0
# 
add_interface hdc1000_s0 avalon end
set_interface_property hdc1000_s0 addressUnits WORDS
set_interface_property hdc1000_s0 associatedClock clock
set_interface_property hdc1000_s0 associatedReset reset
set_interface_property hdc1000_s0 bitsPerSymbol 8
set_interface_property hdc1000_s0 burstOnBurstBoundariesOnly false
set_interface_property hdc1000_s0 burstcountUnits WORDS
set_interface_property hdc1000_s0 explicitAddressSpan 0
set_interface_property hdc1000_s0 holdTime 0
set_interface_property hdc1000_s0 linewrapBursts false
set_interface_property hdc1000_s0 maximumPendingReadTransactions 0
set_interface_property hdc1000_s0 maximumPendingWriteTransactions 0
set_interface_property hdc1000_s0 readLatency 0
set_interface_property hdc1000_s0 readWaitTime 1
set_interface_property hdc1000_s0 setupTime 0
set_interface_property hdc1000_s0 timingUnits Cycles
set_interface_property hdc1000_s0 writeWaitTime 0
set_interface_property hdc1000_s0 ENABLED true
set_interface_property hdc1000_s0 EXPORT_OF ""
set_interface_property hdc1000_s0 PORT_NAME_MAP ""
set_interface_property hdc1000_s0 CMSIS_SVD_VARIABLES ""
set_interface_property hdc1000_s0 SVD_ADDRESS_GROUP ""

add_interface_port hdc1000_s0 avs_s0_address address Input 8
add_interface_port hdc1000_s0 avs_s0_read read Input 1
add_interface_port hdc1000_s0 avs_s0_readdata readdata Output 32
add_interface_port hdc1000_s0 avs_s0_write write Input 1
add_interface_port hdc1000_s0 avs_s0_writedata writedata Input 32
add_interface_port hdc1000_s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment hdc1000_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment hdc1000_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment hdc1000_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment hdc1000_s0 embeddedsw.configuration.isPrintableDevice 0

