# TCL File Generated by Component Editor 16.1
# Wed Nov 21 01:52:44 CET 2018
# DO NOT MODIFY


# 
# StrobeGenAndTimeStamp "StrobeGenAndTimeStamp" v1.0
# Elias Geissler 2018.11.21.01:52:44
# genereates strobe and counts the strobes with time stamp
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module StrobeGenAndTimeStamp
# 
set_module_property DESCRIPTION "genereates strobe and counts the strobes with time stamp"
set_module_property NAME StrobeGenAndTimeStamp
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP SSL
set_module_property AUTHOR "Elias Geissler"
set_module_property DISPLAY_NAME StrobeGenAndTimeStamp
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL StrobeGenAndTimeStamp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file StrobeGenAndTimeStamp.vhd VHDL PATH ../../StrobeGenTimeStamp/src/StrobeGenAndTimeStamp.vhd TOP_LEVEL_FILE
add_fileset_file pkgGlobal.vhd VHDL PATH ../../PkgGlobal/pkgGlobal.vhd


# 
# parameters
# 
add_parameter gClkFreq NATURAL 50000000
set_parameter_property gClkFreq DEFAULT_VALUE 50000000
set_parameter_property gClkFreq DISPLAY_NAME gClkFreq
set_parameter_property gClkFreq TYPE NATURAL
set_parameter_property gClkFreq UNITS None
set_parameter_property gClkFreq ALLOWED_RANGES 0:2147483647
set_parameter_property gClkFreq HDL_PARAMETER true
add_parameter gTimeStampWidth NATURAL 32
set_parameter_property gTimeStampWidth DEFAULT_VALUE 32
set_parameter_property gTimeStampWidth DISPLAY_NAME gTimeStampWidth
set_parameter_property gTimeStampWidth TYPE NATURAL
set_parameter_property gTimeStampWidth UNITS None
set_parameter_property gTimeStampWidth ALLOWED_RANGES 0:2147483647
set_parameter_property gTimeStampWidth HDL_PARAMETER true
add_parameter gResetIsLowActive NATURAL 1
set_parameter_property gResetIsLowActive DEFAULT_VALUE 1
set_parameter_property gResetIsLowActive DISPLAY_NAME gResetIsLowActive
set_parameter_property gResetIsLowActive TYPE NATURAL
set_parameter_property gResetIsLowActive UNITS None
set_parameter_property gResetIsLowActive ALLOWED_RANGES 0:1
set_parameter_property gResetIsLowActive HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 50000000
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink iClk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink inRstAsync reset Input 1


# 
# connection point timing
# 
add_interface timing conduit end
set_interface_property timing associatedClock clock_sink
set_interface_property timing associatedReset ""
set_interface_property timing ENABLED true
set_interface_property timing EXPORT_OF ""
set_interface_property timing PORT_NAME_MAP ""
set_interface_property timing CMSIS_SVD_VARIABLES ""
set_interface_property timing SVD_ADDRESS_GROUP ""

add_interface_port timing oStrobe strobe Output 1
add_interface_port timing oTimeStamp strobe_cnt Output 32

